# Generated by Django 5.0.1 on 2024-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('weight', models.FloatField()),
                ('sweetness', models.FloatField()),
                ('crunchiness', models.FloatField()),
                ('juiciness', models.FloatField()),
                ('ripeness', models.FloatField()),
                ('acidity', models.FloatField()),
                ('quality', models.IntegerField()),
                ('is_user_submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
