# Generated by Django 5.0.1 on 2024-02-03 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applequality',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
