# Generated by Django 5.0.2 on 2024-02-09 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applequality_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applequality',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 14, 38, 14, 784632, tzinfo=datetime.timezone.utc)),
        ),
    ]
